Questão 15
paulanader/react-components-exercises pull request #10
Opened 2022-03-18 13:47 UTC by paulanader

2022-03-18 17:47 UTC, fredsvanelli requested changes

2022-03-18 17:47 UTC, fredsvanelli commented on src/App.tsx
> +            </div>
Insira mais situações possíveis

2022-03-18 17:47 UTC, fredsvanelli commented on src/components/Q2Uppercase copy/index.tsx
> +};
O `for` está errado, porque se a frase tiver 3 palavras, ele vai rodar 4x

2022-03-19 12:31 UTC, paulanader commented on src/components/Q2Uppercase copy/index.tsx
> +};
For está ok

2022-03-19 12:31 UTC, paulanader commented on src/App.tsx
> +            </div>
Incluí mais opções de teste

2022-03-21 13:22 UTC, fredsvanelli submitted a review, later dismissed

2022-03-29 18:46 UTC, fredsvanelli commented
Conflito de merge

2022-03-29 18:47 UTC, fredsvanelli approved these changes

2022-04-05 22:43 UTC, fredsvanelli approved these changes

2022-04-05 23:49 UTC, merged