Questão 19
paulanader/react-components-exercises pull request #13
Opened 2022-03-18 14:13 UTC by paulanader

2022-03-18 19:15 UTC, fredsvanelli requested changes

2022-03-18 19:15 UTC, fredsvanelli commented on src/App.tsx
> +            </div>
Insira mais variações, com números positivos, negativos, zero como dividendo, etc

2022-03-18 19:42 UTC, paulanader commented on src/App.tsx
> +            </div>
Alteração realizada

2022-03-18 21:53 UTC, fredsvanelli requested changes
Conflito de merge

2022-03-29 18:47 UTC, fredsvanelli approved these changes

2022-03-29 18:53 UTC, merged