Questão 25
paulanader/react-components-exercises pull request #14
Opened 2022-03-18 14:18 UTC by paulanader

2022-03-18 19:17 UTC, fredsvanelli requested changes

2022-03-18 19:17 UTC, fredsvanelli commented on src/App.tsx
> +            </div>
1- Como é apenas "ao quadrado", um nome melhor seria `Q20Squared`
2- Insira mais variações, com números negativos e zero

2022-03-18 19:48 UTC, paulanader commented on src/App.tsx
> +            </div>
Alterações realizadas

2022-03-18 21:54 UTC, fredsvanelli requested changes

2022-03-18 21:54 UTC, fredsvanelli commented on src/components/Q20Squared/index.tsx
> +}
O nome da prop `firstNumber` não faz sentido

2022-03-19 12:43 UTC, paulanader commented on src/components/Q20Squared/index.tsx
> +}
Alteração de firstNumber para value.

2022-03-21 13:26 UTC, fredsvanelli approved these changes

2022-03-29 18:48 UTC, fredsvanelli approved these changes

2022-03-29 18:54 UTC, merged