Questão 21
paulanader/react-components-exercises pull request #15
Opened 2022-03-18 14:23 UTC by paulanader

2022-03-18 19:18 UTC, fredsvanelli requested changes

2022-03-18 19:18 UTC, fredsvanelli commented on src/App.tsx
> +            </div>
Insira mais variações, com negativos, positivos e zero em ambas as posições

2022-03-18 19:50 UTC, paulanader commented on src/App.tsx
> +            </div>
Alterações realizadas

2022-03-18 22:01 UTC, fredsvanelli requested changes

2022-03-18 22:01 UTC, fredsvanelli commented on src/App.tsx
> +                />
Faltaram as seguintes situações:
- firstNumber positivo
- firstNumber zero
- secondNumber com casas decimais

Uma forma de se organizar os testes é, sempre comece pelas situações mais comuns de acerto, e depois vá para as mais complexas, forçando descobrir erros. Exemplo:

2 elevado a 2
2 elevado a 4
2 elevado a 0
2 elevado a -2
2 elevado a -5.5
0 elevado a (todas as opções acima)
-2 elevado a (todas as opções acima)
-3.5 elevado a (todas as opções acima)

2022-03-19 12:49 UTC, paulanader commented on src/App.tsx
> +                />
Incluí as opções de teste

2022-03-21 13:27 UTC, fredsvanelli submitted a review, later dismissed

2022-03-29 18:48 UTC, fredsvanelli submitted a review, later dismissed

2022-04-05 22:43 UTC, fredsvanelli approved these changes

2022-04-05 22:43 UTC, merged