Questão 23
paulanader/react-components-exercises pull request #17
Opened 2022-03-18 14:36 UTC by paulanader

2022-03-18 19:22 UTC, fredsvanelli requested changes

2022-03-18 19:22 UTC, fredsvanelli commented on src/components/Q23Random/index.tsx
> +);
Dessa forma só é possível resultados de 1 a 10, nunca zero

2022-03-18 20:00 UTC, paulanader commented on src/components/Q23Random/index.tsx
> +);
Alteração realizada

2022-03-18 22:03 UTC, fredsvanelli requested changes

2022-03-18 22:03 UTC, fredsvanelli commented on src/components/Q23Random/index.tsx
> +const Q23Random: React.FC = () => <span>{Math.floor(Math.random() * 10)}</span>;
Agora só retornam resultados de 0 a 9

2022-03-19 13:08 UTC, paulanader commented on src/components/Q23Random/index.tsx
> +const Q23Random: React.FC = () => <span>{Math.floor(Math.random() * 10)}</span>;
Inclusão feita

2022-03-21 13:30 UTC, fredsvanelli requested changes
Você só desfez a última correção e voltou para o erro anterior

2022-03-24 13:23 UTC, paulanader commented
Eu não tinha feito. push no GitKraken. Alteração realizada.

2022-03-29 18:51 UTC, fredsvanelli requested changes
Continua o mesmo erro inalterado

2022-04-05 22:45 UTC, fredsvanelli approved these changes

2022-04-05 22:45 UTC, merged