Questao 27
paulanader/react-components-exercises pull request #21
Opened 2022-03-21 14:15 UTC by paulanader

Crie um componente que recebe um número X e retorna o seu fatorial

2022-03-29 19:01 UTC, fredsvanelli requested changes
Nesse commit você está deletando a questão 18

2022-03-29 19:01 UTC, fredsvanelli commented on src/components/Q27Factorial/index.tsx
> +    return <span>Não existe fatorial para números decimais</span>;
![image](https://user-images.githubusercontent.com/10292175/160685648-f67d82e1-8f3f-4fcb-be08-5b285cdb0291.png)

2022-03-30 19:23 UTC, paulanader commented
Fiz a burrada de apagar o 18. Tem como reverter ou eu vou precisar refazer?

2022-04-05 22:48 UTC, fredsvanelli approved these changes

2022-04-05 23:53 UTC, merged