Questao 32
paulanader/react-components-exercises pull request #26
Opened 2022-03-21 21:47 UTC by paulanader

Crie um componente que recebe (x, width, height, color) e retorna X retângulos de largura e altura definidos por width e height respectivamente, e com cor de fundo definido por color, alinhados lado a lado

2022-03-30 13:50 UTC, fredsvanelli requested changes

2022-03-30 13:50 UTC, fredsvanelli commented on src/components/Q32Rectangle/index.tsx
> +                className="me-3 col d-inline-flex"
A classe `col` não faz sentido nesse contexto. `col` é apenas utilizado para definir uma coluna dentro de um `row`

2022-03-30 19:50 UTC, paulanader commented on package.json
> +    "styled-components": "^5.3.3",
Retirado

2022-03-30 19:51 UTC, paulanader commented on src/components/Q32Rectangle/index.tsx
> +                className="me-3 col d-inline-flex"
Alteração realizada

2022-04-05 22:54 UTC, fredsvanelli approved these changes

2022-04-05 23:59 UTC, merged