Questão 8
paulanader/react-components-exercises pull request #3
Opened 2022-03-17 19:13 UTC by paulanader

2022-03-17 19:18 UTC, fredsvanelli requested changes

2022-03-17 19:18 UTC, fredsvanelli commented on src/components/Q8StringRepetition/index.tsx
> +    return <span>{phrase}</span>;
Essa lógica está com vários erros. Isso nunca vai funcionar

2022-03-17 19:19 UTC, fredsvanelli commented
Essa branch está com conflito de merge

2022-03-18 01:56 UTC, fredsvanelli approved these changes

2022-03-18 01:56 UTC, fredsvanelli commented on src/components/Q8StringRepetition/index.tsx
> +    }
Está errado, porque se você colocar 5, irá repetir 4x

2022-03-18 01:57 UTC, fredsvanelli requested changes

2022-03-18 01:57 UTC, fredsvanelli commented on src/components/Q8StringRepetition/index.tsx
> +    }
Está errado, porque se você colocar 5, irá repetir 4x

2022-03-18 17:19 UTC, fredsvanelli requested changes

2022-03-18 17:19 UTC, fredsvanelli commented on src/App.tsx
> +            </div>
Insira mais possibilidades:

```
<Q8StringRepetition value="Oi" number={-5} />
<Q8StringRepetition value="Oi" number={0} />
<Q8StringRepetition value="Oi" number={5} />
```

2022-03-18 17:52 UTC, paulanader commented
Inseri as opções de teste.

2022-03-21 13:16 UTC, fredsvanelli requested changes

2022-03-21 13:16 UTC, fredsvanelli commented on src/App.tsx
> +            </div>
Não foi implementado

2022-03-29 18:35 UTC, fredsvanelli approved these changes

2022-03-29 18:46 UTC, merged