Questão 9
paulanader/react-components-exercises pull request #4
Opened 2022-03-17 21:16 UTC by paulanader

2022-03-18 01:59 UTC, fredsvanelli requested changes

2022-03-18 01:59 UTC, fredsvanelli commented on src/components/Q9CharRepeatingWithSpaceAndComma/index.tsx
> +    }
Está errado, porque se você colocar 5, irá repetir 6x

2022-03-18 02:02 UTC, fredsvanelli requested changes

2022-03-18 02:02 UTC, fredsvanelli commented on src/components/Q9CharRepeatingWithSpaceAndComma/index.tsx
> +const Q9CharRepeatingWithSpaceAndComma: React.FC<
Esse nome nāo faz sentido. `Char` significa `1 letra`

2022-03-18 17:21 UTC, fredsvanelli requested changes

2022-03-18 17:21 UTC, fredsvanelli commented on src/components/Q9CharRepeatingWithSpaceAndComma/index.tsx
> +    }
Ao invés de adicionar o `-1`, o que é uma gambiarra. Você tem que tirar o `-1` e iniciar o array como vazio `[]`

2022-03-18 17:22 UTC, fredsvanelli requested changes

2022-03-18 17:22 UTC, fredsvanelli commented on src/App.tsx
> +            </div>
Insira mais possibilidades:

```
<Q9CharRepeatingWithSpaceAndComma value="Oi" number={-5} />
<Q9CharRepeatingWithSpaceAndComma value="Oi" number={0} />
<Q9CharRepeatingWithSpaceAndComma value="Oi" number={5} />
```

2022-03-18 18:03 UTC, paulanader commented on src/App.tsx
> +            </div>
Realizei o teste e verifiquei que tinha o erro no código no componente da questão.

2022-03-18 21:26 UTC, fredsvanelli requested changes

2022-03-18 21:26 UTC, fredsvanelli commented on src/components/Q9CharRepeatingWithSpaceAndComma/index.tsx
> +const Q9CharRepeatingWithSpaceAndComma: React.FC<
Isso não foi corrigido

2022-03-24 12:19 UTC, paulanader commented on src/components/Q9CharRepeatingWithSpaceAndComma/index.tsx
> +    }
Está repetindo {number} vezes.

2022-03-24 12:19 UTC, paulanader commented on src/components/Q9CharRepeatingWithSpaceAndComma/index.tsx
> +const Q9CharRepeatingWithSpaceAndComma: React.FC<
Nome alterado

2022-03-29 18:36 UTC, fredsvanelli approved these changes

2022-04-05 22:38 UTC, fredsvanelli approved these changes

2022-04-05 22:38 UTC, merged