Questão 10
paulanader/react-components-exercises pull request #5
Opened 2022-03-17 21:32 UTC by paulanader

2022-03-18 02:01 UTC, fredsvanelli requested changes

2022-03-18 02:01 UTC, fredsvanelli commented on src/components/Q10TheBiggestCharacter/index.tsx
> +const Q10TheBiggestCharacter: React.FC<IQ10TheBiggestCharacterProps> = ({
Esse nome nāo faz sentido. `Character` significa `1 letra`

2022-03-18 17:24 UTC, fredsvanelli requested changes

2022-03-18 17:24 UTC, fredsvanelli commented on src/App.tsx
> +                />
Esse nome faz menos sentido ainda. Coloca `Q10LongerString`

2022-03-18 18:06 UTC, paulanader commented on src/App.tsx
> +                />
Mudança realizada.

2022-03-18 21:39 UTC, fredsvanelli requested changes
Nada foi alterado

2022-03-28 13:20 UTC, paulanader commented on src/components/Q10LongerString/index.tsx
> +const Q10LongerString: React.FC<IQ10LongerStringProps> = ({
Alteração de nome realizada

2022-03-29 18:36 UTC, fredsvanelli submitted a review, later dismissed

2022-03-29 18:37 UTC, fredsvanelli commented
Conflito de merge

2022-04-05 22:39 UTC, fredsvanelli approved these changes

2022-04-05 22:39 UTC, merged