Questão 13
paulanader/react-components-exercises pull request #8
Opened 2022-03-18 13:06 UTC by paulanader

2022-03-18 17:35 UTC, fredsvanelli requested changes

2022-03-18 17:35 UTC, fredsvanelli commented on src/App.tsx
> +            </div>
Insira todas as possibilidades de acerto e erro

2022-03-18 17:35 UTC, fredsvanelli commented on src/components/Q13ReplacingEvents/index.tsx
> +    change: string;
Esses nomes de prop não fazem sentido. Use `search` e `replace`

2022-03-18 17:35 UTC, fredsvanelli commented on src/components/Q13ReplacingEvents/index.tsx
> +};
Isso está inacreditavelmente enorme. A solução correta tem 1 linha

2022-03-18 18:24 UTC, paulanader commented on src/components/Q13ReplacingEvents/index.tsx
> +};
Alteração feita.

2022-03-18 21:46 UTC, fredsvanelli requested changes
O que eu pedi não foi corrigido

2022-03-19 12:18 UTC, paulanader commented on src/components/Q13ReplacingEvents/index.tsx
> +    change: string;
Alteração realizada

2022-03-19 12:18 UTC, paulanader commented on src/App.tsx
> +            </div>
Incluí as opções

2022-03-21 13:17 UTC, fredsvanelli requested changes
Você pediu uma nova revisão sem nada ter sido alterado

2022-03-24 12:52 UTC, paulanader commented
Eu tinha esquecido de fazer o Push no GitKraken. Subi as alterações agora.

2022-03-29 18:46 UTC, fredsvanelli approved these changes

2022-03-29 18:46 UTC, fredsvanelli commented
Conflito de merge

2022-04-05 22:42 UTC, fredsvanelli approved these changes

2022-04-05 23:47 UTC, merged