Questão 14
paulanader/react-components-exercises pull request #9
Opened 2022-03-18 13:34 UTC by paulanader

2022-03-18 17:39 UTC, fredsvanelli requested changes

2022-03-18 17:39 UTC, fredsvanelli commented on src/App.tsx
> +            </div>
Insira mais situações

2022-03-18 17:39 UTC, fredsvanelli commented on src/components/Q14FirstLetterUppercase/index.tsx
> +};
A solução desse é com 1 linha

2022-03-18 18:41 UTC, paulanader commented on src/components/Q14FirstLetterUppercase/index.tsx
> +};
Alteração realizada

2022-03-19 12:22 UTC, paulanader commented on src/App.tsx
> +            </div>
Incluí opções para verificação.

<Q14FirstLetterUppercase value="MaS QuE LoUcUrA" />
<Q14FirstLetterUppercase value="mas que loucura esse devs" />
 <Q14FirstLetterUppercase value="MAS QUE LOUCURA ESSE DEVS" />
 <Q14FirstLetterUppercase value="mAS qUE lOUCURA eSSE dEVS" />
  <Q14FirstLetterUppercase value="MaS  QuE LoUcUrA" />

2022-03-21 13:21 UTC, fredsvanelli submitted a review, later dismissed

2022-03-22 23:15 UTC, fredsvanelli approved these changes

2022-03-22 23:15 UTC, merged